- hosts: all
  remote_user: root
  tasks:

  - name: Prepare OpenShift home
    file: path=/tmp/openshift state=directory

  - name: Download OpenShift Origin
    unarchive:
      src: https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-server-v1.4.1-3f9807a-linux-64bit.tar.gz
      dest: /tmp/openshift
      remote_src: True
