- hosts: openshift
  remote_user: root
  tasks:

  - include: firewall/firewall.yml
  - include: openshift/openshift.yml
  - include: zookeeper/zookeeper.yml
  - include: kafka/kafka.yml
  - include: mongo/mongo.yml
