- hosts: openshift
  remote_user: fedora
  become: true
  vars:
    project_name: streamshift

  roles:
  - { role: hekonsek.fedora-firewall,0.5 }
  - { role: hekonsek.fedora-docker,0.0 }

  tasks:

  - include: openshift/openshift.yml
  - include: zookeeper/zookeeper.yml
  - include: kafka/kafka.yml
  - include: mongo/mongo.yml
