- hosts: openshift
  remote_user: fedora
  become: true
  tasks:

  - include: firewall/firewall.yml
  - include: openshift/openshift.yml
  - include: zookeeper/zookeeper.yml
  - include: kafka/kafka.yml
  - include: mongo/mongo.yml
