- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Upload pubic SSH key
    ec2_key:
      name: "{{ key_name | default('streamShiftKey') }}"
      key_material: "{{lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub')}}"
      region: eu-central-1
      state: present

  - name: Provision Fedora 25
    ec2:
      instance_type: "{{ instance_type | default('t2.medium') }}"
      region: eu-central-1
      image: ami-bac603d5 # Fedora 25
      wait: yes
      instance_tags:
              name: "{{ instance_name | default('streamShift') }}"
      key_name: "{{ key_name | default('streamShiftKey') }}"