- hosts: openshift
  remote_user: root
  tasks:

  - name: Prepare OpenShift home
    file: path=/usr/openshift state=directory

  - name: Prepare OpenShift runtime directory
    file: path=/var/openshift state=directory

  - name: Download OpenShift Origin
    unarchive:
      src: https://github.com/openshift/origin/releases/download/v1.5.1/openshift-origin-server-v1.5.1-7b451fc-linux-64bit.tar.gz
      dest: /usr/openshift
      remote_src: True

  - name: Install service systemd descriptor
    copy:
      src: openshift.service
      dest: /etc/systemd/system/openshift.service
      mode: 0664

  - name: Make sure OpenShift is running
    systemd:
      name: openshift
      state: started
      enabled: yes
      daemon_reload: yes

  - name: Give OpenShift time to create configuration
    pause:
      seconds: 10

  - name: Make OpenShift configuration readable
    file:
      path: /openshift.local.config
      mode: u=rwX,g=rwX,o=rwX
      recurse: yes

  - name: Install OpenShift client
    copy:
      remote_src: True
      src: /usr/openshift/openshift-origin-server-v1.5.1-7b451fc-linux-64bit/oc
      dest: /usr/bin/oc
      mode: 0555

  - name: Log in as 'system:admin'
    command: /usr/bin/oc --config=/openshift.local.config/master/admin.kubeconfig login -u system:admin

  - name: Add cluster read rights to 'admin' user
    command: /usr/bin/oc --config=/openshift.local.config/master/admin.kubeconfig adm policy add-cluster-role-to-user cluster-reader admin